import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
import Ajv from 'ajv/dist/2020.js';
import addFormats from 'ajv-formats';
const schema = JSON.parse(readFileSync('specification/draft-01/envelope.schema.json'));
const events = JSON.parse(readFileSync('specification/draft-01/examples/counter.json'));
const ajv = new Ajv({ strict: true, allErrors: true });
addFormats(ajv);
const validate = ajv.compile(schema);
for (const event of events) assert(validate(event), JSON.stringify(validate.errors));
const find = kind => structuredClone(events.find(e => e.type === `dasp.${kind}.v1`));
let negatives = 0;
function invalid(kind, change) {
  const event = find(kind); change(event);
  assert.equal(validate(event), false, `Expected invalid ${kind}`); negatives++;
}
invalid('command',e=>delete e.source);
invalid('command',e=>e.specversion='1.0.2');
invalid('command',e=>e.source='/relative/source');
invalid('command',e=>delete e.requestid);
invalid('command',e=>e.data.text='chat field outside profile');
invalid('command',e=>e.data.input.amount=1.5);
invalid('command',e=>e.data.input.amount=9007199254740992);
invalid('command',e=>e.data=null);
invalid('command',e=>e.data_base64='e30=');
invalid('command',e=>e.bad_extension='invalid context name');
invalid('command',e=>e.extension={nested:true});
invalid('command',e=>e.extension=2147483648);
invalid('receipt',e=>e.data.admission_sequence=null);
invalid('receipt',e=>e.data.error={code:'unavailable',message:'x',retryable:true});
invalid('outcome',e=>e.data.outcome.status='uncertain');
invalid('update',e=>e.data.sequence=0);
invalid('updates',e=>e.data.events[0].type='dasp.progress.v1');
invalid('updates.read',e=>e.data.limit=101);
const extended=find('command');
Object.assign(extended,{subject:extended.data.session_id,time:'2026-09-25T12:00:00Z',traceparent:'00-example',customflag:true});
assert(validate(extended),JSON.stringify(validate.errors));
// Cross-message fixture checks: shape validation cannot prove these properties.
const updates=events.filter(e=>e.type==='dasp.update.v1');
assert.deepEqual(updates.map(e=>e.data.sequence),[1,2,3]);
const page=find('updates').data;
assert.deepEqual(page.events,updates.slice(1));
assert.equal(page.next,page.events.at(-1).data.sequence);
assert.equal(page.head,3);
assert.equal(find('receipt').data.admission_sequence,updates[0].data.sequence);
assert.deepEqual(find('outcome').data.outcome,updates.at(-1).data.payload);
assert.equal(find('outcome').data.sequence,updates.at(-1).data.sequence);
assert.equal(find('view').data.state.value,updates[1].data.payload.data.value);
assert.equal(find('command').requestid,find('receipt').requestid);
assert.equal(new Set(events.map(e=>e.source+'\0'+e.id)).size,events.length);
const counterSchema=JSON.parse(readFileSync('specification/draft-01/examples/counter-profile.schema.json'));
ajv.addSchema(counterSchema);
const profileInput=ajv.compile({$ref:counterSchema.$id+'#/$defs/input'});
const profileState=ajv.compile({$ref:counterSchema.$id+'#/$defs/state'});
assert(profileInput(find('command').data.input));
assert(profileState(find('view').data.state));
assert(profileState(find('outcome').data.outcome.output));
assert(profileState(updates[1].data.payload.data));
assert.equal(profileInput({amount:1000001}),false);
assert.equal(profileInput({amount:3,text:'not a counter field'}),false);
console.log(`DASP draft: ${events.length} valid events, ${negatives} rejected shapes, extension and fixture consistency checks passed.`);
